M1_TR-3 Setup CI/CD and checkers
framgia/sph-sim-jms pull request #2
Opened 2023-08-07 04:33 UTC by jasonchuasun

### Related Issue
- [Backlog](https://framgiaph.backlog.com/view/M1_TR-3)

### Context
- set up sun-ci.yaml file for running build and test
- commands: 
  - `npm i`

### Test Executed
- [ ] Unit Test
- [ ] Functional Test

### Screenshot

### Nature of task
- [ ] New Implementation
- [ ] Bug
- [ ] Refactoring

### Risks
- [ ] Affecting other functions

2023-08-11 02:09 UTC, jeremiahC commented on package-lock.json
we will be using yarn.lock more, so please delete

2023-08-11 02:11 UTC, jeremiahC commented on web/package-lock.json
Please delete since we will use yarn

2023-08-11 02:22 UTC, jeremiahC requested changes
Please add test_result and coverage. Like this:
```
  stage: test
  image: sunasteriskrnd/php-workspace:7.4
  workspace: shared
  script:
  - phpunit --coverage-clover ./coverage.xml --log-junit ./junit.xml
  coverage:
    type: clover
    path: coverage.xml
  test_result:
    type: junit
    path: junit.xml  
  depends_on:
    - build php
```

Reference: https://ci.sun-asterisk.com/docs/guide/yaml/#configuration-example

2023-08-24 05:12 UTC, arden-dave submitted a review, later dismissed

2023-08-24 05:13 UTC, nicoleamber submitted a review, later dismissed

2023-08-24 05:23 UTC, jeremiahC approved these changes

2023-08-24 05:26 UTC, NiloJr-sun submitted a review, later dismissed

2023-08-24 05:27 UTC, jeremiahC requested changes
- I forgot to comment, please add `post-lint` stage. Even though we have husky for pre-commit. Just another layer of checking, please add linter in the ci config

2023-08-24 05:32 UTC, jeremiahC commented on .sun-ci.yml
> +      - yarn install
setting up the environment should be done on the build stage. Also, Please include frontend as well, you can separete the stages for testing FE and BE.

2023-08-24 05:33 UTC, jeremiahC commented on .sun-ci.yml
> +      - yarn eslint .
can you separate the stages

- build (preparing your backend and fe)
   - Suggestion: if you want to run one command for all, you can create a bash sript and will run both fe and be commands
- post-lint (for running linter)
- test-be 
- test-fe

2023-08-25 02:33 UTC, jeremiahC requested changes

2023-08-25 02:33 UTC, jeremiahC commented on .sun-ci.yml
For the yarn install, can it be done on the build stage? I think you don't need to yarn install all the time in different stages.

2023-08-25 02:59 UTC, jeremiahC approved these changes

2023-08-25 03:04 UTC, merged